version: 0.2

env:
  variables:
    S3_BUCKET: "codedeploymentlambda"
    PACKAGE: "github.com/shashankp1992/go"

phases:
  install:
    commands:
      # Print all environment variables (handy for AWS CodeBuild logs)
      - env

  build:
    commands:
      # Build our go application
      - go get github.com/aws/aws-lambda-go/events
      - go get github.com/aws/aws-lambda-go/lambda
      - go build main.go
      - zip -m maindeploy.zip main

  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name codedeployment --zip-file fileb://maindeploy.zip
      - echo "DONE!!"

